pcm.m17s_dmix {
    type dmix
    ipc_key 17017
    ipc_perm 0660
    slave {
        pcm "hw:S905XP212,0"
        format S16_LE
        rate 48000
        channels 2
        period_size 1024
        buffer_size 8192
    }
}

ctl.m17s_dmix {
    type hw
    card S905XP212
}
